version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - postgres
      - mongo
      - redis
    networks:
      - civic-network

  postgres:
    image: postgres:15
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - civic-network

  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db
    networks:
      - civic-network

  redis:
    image: redis:7-alpine
    networks:
      - civic-network

volumes:
  postgres-data:
  mongo-data:

networks:
  civic-network:
    driver: bridge