services:
  backend:
    build: .
    container_name: civic_backend
    ports:
      - "3000:3000"
    environment:
      - PORT=5000
      - JWT_SECRET=your_jwt_secret
      - JWT_REFRESH_SECRET=your_refresh_secret
      - POSTGRES_URL=postgresql://postgres:aloice@aloice:5432/civicdb
      - MONGODB_URI=mongodb://mongo:27017/civicdb
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - mongo
      - redis

  postgres:
    image: postgres:15
    container_name: civic_postgres
    restart: always
    environment:
      POSTGRES_DB: civicdb
      POSTGRES_USER: aloice
      POSTGRES_PASSWORD: aloice
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    container_name: civic_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  redis:
    image: redis:7
    container_name: civic_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
  mongodata:
